image: ubuntu/18.04
packages:
  - libboost-test-dev
  - valgrind
  - libsamplerate0-dev
  - curl
sources:
  - hg+https://hg.sr.ht/~breakfastquay/bqresample
tasks:
  - setup: |
      hg clone https://hg.sr.ht/~breakfastquay/bqvec
  - build: |
      cd bqresample
      build/run-platform-tests.sh linux
triggers:
  - action: email
    condition: always
    to: chris.cannam@breakfastquay.com
