language: cpp

os:
  - linux
  - osx

addons:
  apt:
    packages:
      - libboost-test-dev
      - valgrind
#      - libsamplerate0-dev

before_install:
  - if [[ "$TRAVIS_OS_NAME" = "osx" ]] ; then brew install libsamplerate ; fi
#  - if [[ "$TRAVIS_OS_NAME" = "linux" ]] ; then apt-cache showpkg libsamplerate0-dev ; fi
  - if [[ "$TRAVIS_OS_NAME" = "linux" ]] ; then ( cd .. ; curl -O http://www.mega-nerd.com/SRC/libsamplerate-0.1.9.tar.gz && tar xvzf libsamplerate-0.1.9.tar.gz && cd libsamplerate-0.1.9 && ./configure && make && sudo make install )
  - ( cd .. ; git clone https://github.com/breakfastquay/bqvec )

script:
  - ./build/run-platform-tests.sh "$TRAVIS_OS_NAME"


